# This is a basic workflow to help you get started with Actions

name: Deploy_doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code repo
        uses: actions/checkout@v4

      -  uses: mattnotmitt/doxygen-action@v1.9.2
         with:
          # These are default values, but included for clarity
          doxyfile-path: ./Doxyfile
          working-directory: .

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.CODE_DOCUMENTATION_WRITE_PRIV }}
        with:
          source-directory: html/
          destination-github-username: 'Leeds-Spherical-Dynamo'
          destination-repository-name: 'code-documentation'
          user-email: user@leeds.ac.uk
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: gh-pages
